---
title: "Midterm Project"
author: "Jenny Geng"
date: "2025-10-09"
output: pdf_document
---

Data Analysis and Preparation
```{r}
# 1. Load Libraries
library(tidyverse)

# 2. Load and Merge Datasets
sales_data <- read.csv("Sale2025.csv")
res_data <- read.csv("Mas25.csv")

full_data <- inner_join(sales_data, res_data, by = c("Parcel" = "PARCEL"))
head(full_data)
```

```{r}
# 3. Clean and Prepare Data

# create a list of all column names that should be numbers
numeric_columns <- c("SalePrice", "SQFT", "YEAR", "STORIES", "ROOMS", "BATHFIXTUR", "PATIONUMBE", "GARAGECAPA", "POOLAREA")

model_data <- full_data %>%
  # convert data types for all necessary columns
  mutate(
    across(all_of(numeric_columns), as.numeric),
    SFRCONDO = as.factor(trimws(SFRCONDO))
    ) %>%
  # filter to keep SalePrice greater than $1000 and SQFT greater than 100 sqft
  filter(
    SalePrice > 1000,
    SQFT > 100
  ) %>%
  # keep only columns needed for the model
  select(all_of(numeric_columns), SFRCONDO) %>%
  # remove rows with remaining missing values
  na.omit()

head(model_data)
```

```{r}
# 4. Exploratory Data Visualization
model_data %>%
  mutate(SalePrice_capped = ifelse(SalePrice > 1000000, 1000000, SalePrice)) %>%

  ggplot(aes(x = SalePrice_capped)) +
  geom_histogram(bins = 50, fill = "skyblue", color = "black") +
  
  scale_x_continuous(
    breaks = seq(0, 1000000, by = 250000),
    labels = c("$0", "$250,000", "$500,000", "$750,000", "$1,000,000+")) +
  
  labs(title = "Distribution of Home Sale Prices in Tucson, AZ", 
       x = "Sale Price", 
       y = "Frequency")
```


Stepwise Model Selection
```{r}
# fit the full model with all candidate predictors
full_model <- lm(SalePrice ~ ., data = model_data)
require(faraway)
sumary(full_model)
```

``` {r}
# perform backward stepwise selection and find one with the lowest AIC
best_model <- step(full_model, direction = "backward", trace = 0)
summary(best_model)
```

```{r}
# perform ANOVA test to see if the two models are significantly different
anova(full_model, best_model)
```
